Review
KznRkjp/go-keeper pull request #3
Opened 2024-10-31 09:27 UTC by KznRkjp

2024-10-31 19:24 UTC, s-shpak requested changes

2024-10-31 19:24 UTC, s-shpak commented on bin/server/mac/go-keeper-server
Этого не должно быть в репозитории

2024-11-01 12:45 UTC, KznRkjp commented on bin/server/mac/go-keeper-server
Я  исходил из:

> Дополнительные требования:
> клиент должен распространяться в виде CLI-приложения с возможностью запуска на платформах Windows, Linux и Mac OS;
Удалю потом )

2024-11-07 21:38 UTC, s-shpak approved these changes

2024-11-08 09:02 UTC, merged